# Generated by Django 2.0 on 2019-05-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Qustions',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('Rate_us', models.CharField(blank=True, choices=[('a', 'Very good'), ('b', 'good'), ('c', 'Average'), ('d', 'Bad')], max_length=1)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Question'),
        ),
    ]
