# Generated by Django 2.0 on 2019-05-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedbackmodel',
            name='name',
        ),
    ]
